.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH SF 1 "October 28, 2000"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
herekitty \- amuse cat using a hyperactive xclock
.SH SYNOPSIS
.B herekitty
.SH DESCRIPTION
.LP
The 
.B herekitty
program uses the SUBTERFUGUE TimeWarp trick to run a (full screen) xclock at
high speed, for your cat's amusement.
.SH SEE ALSO
.BR sf (1),
.BR xclock (1).
